version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sap_repoProject
  gitServerName: k
  gitUrl: https://github.com/Kruthika-K-IBM
  gitUsername: Kruthika-K-IBM
  gitBranch: main
- name: LibPkgNoDependency
  gitServerName: k
  gitUrl: https://github.com/RoopaSandeep-Desai-IBM
  gitUsername: Kruthika-K-IBM
  gitBranch: main
